# Packages

In [42]:
import math
import numpy as np
from sklearn import linear_model
from os import mkdir
import string
from collections import Counter 
from random import shuffle

In [43]:
help (mkdir)
linear_model.LinearRegression?

Help on built-in function mkdir in module nt:

mkdir(path, mode=511, *, dir_fd=None)
    Create a directory.
    
    If dir_fd is not None, it should be a file descriptor open to a directory,
      and path should be relative; path will then be relative to that directory.
    dir_fd may not be implemented on your platform.
      If it is unavailable, using it will raise a NotImplementedError.
    
    The mode argument is ignored on Windows.



Init signature:
linear_model.LinearRegression(
    *,
    fit_intercept=True,
    copy_X=True,
    n_jobs=None,
    positive=False,
)
Docstring:     
Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, ..., wp)
to minimize the residual sum of squares between the observed targets in
the dataset, and the targets predicted by the linear approximation.

Parameters
----------
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (i.e. data is expected to be centered).

copy_X : bool, default=True
    If True, X will be copied; else, it may be overwritten.

n_jobs : int, default=None
    The number of jobs to use for the computation. This will only provide
    speedup in case of sufficiently large problems, that is if firstly
    `n_targets > 1` and secondly `X` is sparse or if `positive` is set
    to `True`. ``None`` means 1 unless in

In [44]:
print(np.__version__)

2.0.2


In [45]:
from inspect import getsourcelines # obtenir le code source de fonctions
getsourcelines(linear_model.LinearRegression)

(['class LinearRegression(MultiOutputMixin, RegressorMixin, LinearModel):\n',
  '    """\n',
  '    Ordinary least squares Linear Regression.\n',
  '\n',
  '    LinearRegression fits a linear model with coefficients w = (w1, ..., wp)\n',
  '    to minimize the residual sum of squares between the observed targets in\n',
  '    the dataset, and the targets predicted by the linear approximation.\n',
  '\n',
  '    Parameters\n',
  '    ----------\n',
  '    fit_intercept : bool, default=True\n',
  '        Whether to calculate the intercept for this model. If set\n',
  '        to False, no intercept will be used in calculations\n',
  '        (i.e. data is expected to be centered).\n',
  '\n',
  '    copy_X : bool, default=True\n',
  '        If True, X will be copied; else, it may be overwritten.\n',
  '\n',
  '    n_jobs : int, default=None\n',
  '        The number of jobs to use for the computation. This will only provide\n',
  '        speedup in case of sufficiently large problems,

In [46]:
import time

# Introduction à Python, Numpy et Scipy

## Nextpower

In [47]:
# Method 1
def nextpower(n, m = 0):
    while 2**m  < n :
        m += 1
    return(2**m)

In [48]:
# Method 2
def nextpowerbis(n):
    """Compute the next power of 2 of n."""
    sol = 1
    while sol < n:
        sol *= 2
    return sol

In [49]:
print(nextpower(5))
print(nextpowerbis(5))

8
8


In [50]:
t = time.time()
print(nextpower(10000000000000))
print(time.time() - t)

17592186044416
0.0


In [51]:
t = time.time()
print(nextpowerbis(10000000000000))
print(time.time() - t)

17592186044416
0.0016291141510009766


## Génération mot

In [52]:
alphabet = string.ascii_lowercase
print(alphabet)

abcdefghijklmnopqrstuvwxyz


In [53]:
# Generate cfilorux
x = slice(2, -1, 3)
alphabet[x]

'cfilorux'

In [54]:
# Generate vxz : method 1
x = slice(21, 26, 2)
alphabet[x]

'vxz'

In [55]:
# Generate vxz : method 2
print(alphabet[-5::2])

vxz


In [56]:
# Generate vxz : method 3
alphabet_list = list(alphabet)
index_v = alphabet_list.index('v')
index_x = alphabet_list.index('x')
index_z = alphabet_list.index('z')
vzx = alphabet_list[index_v] + alphabet_list[index_x] + alphabet_list[index_z]
print(vzx)

vxz


## Pi

In [57]:
print("Pi with 9 decimals:", round(math.pi, 9))

Pi with 9 decimals: 3.141592654


## Count occurences 

In [58]:
s="HelLo WorLd!!"

In [59]:
print(Counter(s))

Counter({'L': 2, 'o': 2, '!': 2, 'H': 1, 'e': 1, 'l': 1, ' ': 1, 'W': 1, 'r': 1, 'd': 1})


## Encodage of Cezar

In [60]:
# Try shuffle
shuffle(alphabet_list)
print(alphabet_list)

['e', 'q', 'z', 'd', 'w', 's', 'a', 'o', 'p', 'f', 'b', 'm', 'y', 'n', 'c', 'i', 'l', 'r', 'v', 'x', 'g', 't', 'h', 'j', 'k', 'u']


In [61]:
# Try shuffle to index
indexes = list(range(len(alphabet)))
shuffle(indexes)
print(indexes)

[6, 2, 20, 12, 0, 7, 23, 25, 3, 16, 19, 4, 14, 10, 22, 21, 24, 17, 11, 9, 1, 18, 8, 13, 5, 15]


In [62]:
def coding(message, rosette, alphabet):
    """encodage"""
    message_coded = ""
    for i, letter in enumerate(message):
        if letter in alphabet:
            message_coded += rosette[letter]
        else:
            message_coded += letter
    message_coded = message_coded
    return message_coded

In [63]:
rosette_forward = {}
rosette_backward = {}

for i, letter in enumerate(alphabet):
    rosette_forward[letter] = alphabet[indexes[i]]
    rosette_backward[alphabet[indexes[i]]] = letter

rosette_forward[" "] = " "
rosette_backward[" "] = " "

print(rosette_forward)
print(rosette_backward)

{'a': 'g', 'b': 'c', 'c': 'u', 'd': 'm', 'e': 'a', 'f': 'h', 'g': 'x', 'h': 'z', 'i': 'd', 'j': 'q', 'k': 't', 'l': 'e', 'm': 'o', 'n': 'k', 'o': 'w', 'p': 'v', 'q': 'y', 'r': 'r', 's': 'l', 't': 'j', 'u': 'b', 'v': 's', 'w': 'i', 'x': 'n', 'y': 'f', 'z': 'p', ' ': ' '}
{'g': 'a', 'c': 'b', 'u': 'c', 'm': 'd', 'a': 'e', 'h': 'f', 'x': 'g', 'z': 'h', 'd': 'i', 'q': 'j', 't': 'k', 'e': 'l', 'o': 'm', 'k': 'n', 'w': 'o', 'v': 'p', 'y': 'q', 'r': 'r', 'l': 's', 'j': 't', 'b': 'u', 's': 'v', 'i': 'w', 'n': 'x', 'f': 'y', 'p': 'z', ' ': ' '}


In [64]:
message = "Le monde n'est pas à l'abri d'une gouvernance par le robot"

In [65]:
# message = "Tu les crois malades ?".decode('utf8')
print("Message original:\n" + message + "\n")
message_encoded = coding(message, rosette_forward, alphabet)
print("Message codé:" + "\n"+ message_encoded + "\n")
message_decoded = coding(message_encoded, rosette_backward, alphabet)
print("Message décodé:" + "\n"+ message_decoded  + "\n")
print("Est ce que le message décodé est identique à l'original? " + str(message_decoded==message))

Message original:
Le monde n'est pas à l'abri d'une gouvernance par le robot

Message codé:
La owkma k'alj vgl à e'gcrd m'bka xwbsarkgkua vgr ea rwcwj

Message décodé:
Le monde n'est pas à l'abri d'une gouvernance par le robot

Est ce que le message décodé est identique à l'original? True


## Calculate multiplication

In [66]:
# Method 1
def indexed_product_1(n):
    """Naive version"""
    multiplication = 2
    for k in range(1,n+1) :
        multiplication *= (4*k**2) / (4*k**2 - 1)
    return multiplication

In [67]:
# Method 2
def indexed_product_2(n):
    """better version."""
    result = 2.
    for k in range(1, n + 1, 1):
        int = 4 * k ** 2
        result *= int / (int - 1.)
    return result

In [68]:
# Method 3 : recursive function 
def indexed_product_3(n):
    """lame version."""
    if n == 1 : 
        return 8. / 3.
    else :
        sqrpart = 4 * n ** 2
        return ((sqrpart / sqrpart - 1.) * indexed_product_3(n - 1))

In [69]:
# Method 4 : numpy
def indexed_product_4(n) : 
    sol = np.arange(1, n + 1)
    sol = sol ** 2
    sol = 4. * sol / (4. * sol - 1.)
    return 2 * np.prod(sol)

In [70]:
t = time.time()
indexed_product_1(2000)
print(time.time() - t)

t = time.time()
indexed_product_2(2000)
print(time.time() - t)

t = time.time()
indexed_product_3(2000)
print(time.time() - t)

t = time.time()
indexed_product_4(2000)
print(time.time() - t)

0.003116607666015625
0.004243612289428711
0.003408670425415039
0.0


# Quicksort

In [71]:
def quicksort(l):
    """ a sorting algorithm with a pivot value"""
    if len(l) <= 1:
        return l
    else:
        pivot = l.pop()
        less = []
        greater = []
        for x in l:
            if x <= pivot:
                less.append(x) # append 'x' to 'less'
            else:
                greater.append(x) # append 'x' to 'greater'
        return less + [pivot] + greater  # concatenate quicksort(less), pivot and quicksort(greater)

In [72]:
l = [1,10,3,8,4,100,0,20]
quicksort(l)

[1, 10, 3, 8, 4, 0, 20, 100]

## Création d'une matrice et modification

In [73]:
a = [1,2]
b = [4,5]
np.matrix([a, b])

matrix([[1, 2],
        [4, 5]])

In [74]:
matrix = np.random.randint(low = -1 , high = 2, size = (5,6))
np.matrix(matrix)

matrix([[-1, -1,  1,  1,  1,  0],
        [ 1, -1,  1, -1,  0,  1],
        [ 0,  0,  1,  1, -1,  1],
        [ 1,  0,  1, -1, -1,  0],
        [ 0,  1,  1,  0,  0, -1]], dtype=int32)

In [75]:
matrix = np.random.uniform(-1,1, size = (5,6))
print(matrix)

[[ 0.95438045  0.23340692 -0.26669288 -0.85527608  0.83095125  0.1946659 ]
 [-0.25923509 -0.04489997 -0.37447616 -0.17966263 -0.80549707 -0.86344521]
 [ 0.91463248  0.40527479  0.16655204 -0.80187045 -0.60097416  0.99136076]
 [-0.19879354  0.22460191  0.46507551  0.84912327 -0.97052831  0.9706077 ]
 [ 0.9241564   0.33165439 -0.37911334 -0.9231531  -0.87400688  0.25486797]]


In [76]:
matrix[:, 0] # All rows, 1 column

array([ 0.95438045, -0.25923509,  0.91463248, -0.19879354,  0.9241564 ])

In [77]:
m_sol1 = matrix.copy()
m_sol1[:, 0] = matrix[:, 0] - 2 * matrix[:, 1]
m_sol1[:, 2] = matrix[:, 2] - 2 * matrix[:, 3]
m_sol1[:, 4] = matrix[:, 4] - 2 * matrix[:, 5]

In [78]:
m_sol1[1,:]

array([-0.16943514, -0.04489997, -0.0151509 , -0.17966263,  0.92139335,
       -0.86344521])

In [79]:
m_sol1[m_sol1 <= 0] = 0
print(m_sol1)
print(m_sol1)

[[0.48756661 0.23340692 1.44385927 0.         0.44161945 0.1946659 ]
 [0.         0.         0.         0.         0.92139335 0.        ]
 [0.1040829  0.40527479 1.77029295 0.         0.         0.99136076]
 [0.         0.22460191 0.         0.84912327 0.         0.9706077 ]
 [0.26084762 0.33165439 1.46719286 0.         0.         0.25486797]]
[[0.48756661 0.23340692 1.44385927 0.         0.44161945 0.1946659 ]
 [0.         0.         0.         0.         0.92139335 0.        ]
 [0.1040829  0.40527479 1.77029295 0.         0.         0.99136076]
 [0.         0.22460191 0.         0.84912327 0.         0.9706077 ]
 [0.26084762 0.33165439 1.46719286 0.         0.         0.25486797]]


## Création et modification d'une matrice complexe

In [80]:
matrix = np.random.uniform(-1,1, size =(5,20))
print(matrix)

[[ 0.63497045  0.38793369  0.22054834 -0.70429076  0.08406056  0.58011941
   0.11689041  0.26760128  0.01511476  0.46566389  0.18749348 -0.20268746
   0.98097152 -0.7921629  -0.31119762 -0.50381613  0.15185641 -0.2915337
   0.16166679  0.7094321 ]
 [ 0.11328223 -0.3720632  -0.58190238 -0.37379553 -0.40102782 -0.15654236
  -0.14288504 -0.73025311 -0.57839902  0.96759554  0.27935776  0.174361
  -0.62575146 -0.28497753 -0.37542093 -0.91577344 -0.40403186  0.82685221
  -0.73995288 -0.31028535]
 [ 0.33294291  0.76706749 -0.60360958  0.75485371 -0.9151463  -0.82377619
  -0.19111408  0.28383988 -0.81377746  0.49592646 -0.91277246  0.46090142
   0.87551661  0.71474528 -0.31401295  0.9109428   0.85428801  0.37048985
  -0.40417534 -0.20556919]
 [-0.26274067 -0.3671024  -0.89100236 -0.61248269 -0.14692341 -0.21800236
   0.14622595  0.05982875  0.75718419  0.05383107  0.25520755  0.27589534
   0.96503461 -0.82726796  0.02059259 -0.22293092 -0.2180614   0.54172843
   0.57210812 -0.09184775]
 [ 0.47