# Packages

In [2]:
import math
import numpy as np
from sklearn import linear_model
from os import mkdir
import string
from collections import Counter 
from random import shuffle

In [3]:
help (mkdir)
linear_model.LinearRegression?

Help on built-in function mkdir in module nt:

mkdir(path, mode=511, *, dir_fd=None)
    Create a directory.
    
    If dir_fd is not None, it should be a file descriptor open to a directory,
      and path should be relative; path will then be relative to that directory.
    dir_fd may not be implemented on your platform.
      If it is unavailable, using it will raise a NotImplementedError.
    
    The mode argument is ignored on Windows.



Init signature:
linear_model.LinearRegression(
    *,
    fit_intercept=True,
    copy_X=True,
    n_jobs=None,
    positive=False,
)
Docstring:     
Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, ..., wp)
to minimize the residual sum of squares between the observed targets in
the dataset, and the targets predicted by the linear approximation.

Parameters
----------
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (i.e. data is expected to be centered).

copy_X : bool, default=True
    If True, X will be copied; else, it may be overwritten.

n_jobs : int, default=None
    The number of jobs to use for the computation. This will only provide
    speedup in case of sufficiently large problems, that is if firstly
    `n_targets > 1` and secondly `X` is sparse or if `positive` is set
    to `True`. ``None`` means 1 unless in

In [4]:
print(np.__version__)

2.0.2


In [5]:
from inspect import getsourcelines # obtenir le code source de fonctions
getsourcelines(linear_model.LinearRegression)

(['class LinearRegression(MultiOutputMixin, RegressorMixin, LinearModel):\n',
  '    """\n',
  '    Ordinary least squares Linear Regression.\n',
  '\n',
  '    LinearRegression fits a linear model with coefficients w = (w1, ..., wp)\n',
  '    to minimize the residual sum of squares between the observed targets in\n',
  '    the dataset, and the targets predicted by the linear approximation.\n',
  '\n',
  '    Parameters\n',
  '    ----------\n',
  '    fit_intercept : bool, default=True\n',
  '        Whether to calculate the intercept for this model. If set\n',
  '        to False, no intercept will be used in calculations\n',
  '        (i.e. data is expected to be centered).\n',
  '\n',
  '    copy_X : bool, default=True\n',
  '        If True, X will be copied; else, it may be overwritten.\n',
  '\n',
  '    n_jobs : int, default=None\n',
  '        The number of jobs to use for the computation. This will only provide\n',
  '        speedup in case of sufficiently large problems,

In [6]:
import time

# 1.  Introduction à Python, Numpy et Scipy

## Nextpower

In [7]:
# Method 1
def nextpower(n, m = 0):
    while 2**m  < n :
        m += 1
    return(2**m)

In [8]:
# Method 2
def nextpowerbis(n):
    """Compute the next power of 2 of n."""
    sol = 1
    while sol < n:
        sol *= 2
    return sol

In [9]:
print(nextpower(5))
print(nextpowerbis(5))

8
8


In [10]:
t = time.time()
print(nextpower(10000000000000))
print(time.time() - t)

17592186044416
0.0


In [11]:
t = time.time()
print(nextpowerbis(10000000000000))
print(time.time() - t)

17592186044416
0.0009982585906982422


## Génération mot

In [12]:
alphabet = string.ascii_lowercase
print(alphabet)

abcdefghijklmnopqrstuvwxyz


In [13]:
# Generate cfilorux
x = slice(2, -1, 3)
alphabet[x]

'cfilorux'

In [14]:
# Generate vxz : method 1
x = slice(21, 26, 2)
alphabet[x]

'vxz'

In [15]:
# Generate vxz : method 2
print(alphabet[-5::2])

vxz


In [16]:
# Generate vxz : method 3
alphabet_list = list(alphabet)
index_v = alphabet_list.index('v')
index_x = alphabet_list.index('x')
index_z = alphabet_list.index('z')
vzx = alphabet_list[index_v] + alphabet_list[index_x] + alphabet_list[index_z]
print(vzx)

vxz


## Pi

In [17]:
print("Pi with 9 decimals:", round(math.pi, 9))

Pi with 9 decimals: 3.141592654


## Count occurences 

In [18]:
s="HelLo WorLd!!"

In [19]:
print(Counter(s))

Counter({'L': 2, 'o': 2, '!': 2, 'H': 1, 'e': 1, 'l': 1, ' ': 1, 'W': 1, 'r': 1, 'd': 1})


## Encodage of Cezar

In [20]:
# Try shuffle
shuffle(alphabet_list)
print(alphabet_list)

['i', 'o', 'g', 'v', 'd', 'y', 'k', 'e', 'q', 'u', 'h', 'w', 's', 'l', 'p', 'b', 'r', 'z', 't', 'n', 'x', 'a', 'j', 'c', 'f', 'm']


In [21]:
# Try shuffle to index
indexes = list(range(len(alphabet)))
shuffle(indexes)
print(indexes)

[13, 1, 23, 6, 3, 0, 8, 21, 18, 10, 16, 7, 22, 9, 15, 17, 12, 25, 20, 4, 5, 19, 24, 14, 11, 2]


In [22]:
def coding(message, rosette, alphabet):
    """encodage"""
    message_coded = ""
    for i, letter in enumerate(message):
        if letter in alphabet:
            message_coded += rosette[letter]
        else:
            message_coded += letter
    message_coded = message_coded
    return message_coded

In [23]:
rosette_forward = {}
rosette_backward = {}

for i, letter in enumerate(alphabet):
    rosette_forward[letter] = alphabet[indexes[i]]
    rosette_backward[alphabet[indexes[i]]] = letter

rosette_forward[" "] = " "
rosette_backward[" "] = " "

print(rosette_forward)
print(rosette_backward)

{'a': 'n', 'b': 'b', 'c': 'x', 'd': 'g', 'e': 'd', 'f': 'a', 'g': 'i', 'h': 'v', 'i': 's', 'j': 'k', 'k': 'q', 'l': 'h', 'm': 'w', 'n': 'j', 'o': 'p', 'p': 'r', 'q': 'm', 'r': 'z', 's': 'u', 't': 'e', 'u': 'f', 'v': 't', 'w': 'y', 'x': 'o', 'y': 'l', 'z': 'c', ' ': ' '}
{'n': 'a', 'b': 'b', 'x': 'c', 'g': 'd', 'd': 'e', 'a': 'f', 'i': 'g', 'v': 'h', 's': 'i', 'k': 'j', 'q': 'k', 'h': 'l', 'w': 'm', 'j': 'n', 'p': 'o', 'r': 'p', 'm': 'q', 'z': 'r', 'u': 's', 'e': 't', 'f': 'u', 't': 'v', 'y': 'w', 'o': 'x', 'l': 'y', 'c': 'z', ' ': ' '}


In [24]:
message = "Le monde n'est pas à l'abri d'une gouvernance par le robot"

In [25]:
# message = "Tu les crois malades ?".decode('utf8')
print("Message original:\n" + message + "\n")
message_encoded = coding(message, rosette_forward, alphabet)
print("Message codé:" + "\n"+ message_encoded + "\n")
message_decoded = coding(message_encoded, rosette_backward, alphabet)
print("Message décodé:" + "\n"+ message_decoded  + "\n")
print("Est ce que le message décodé est identique à l'original? " + str(message_decoded==message))

Message original:
Le monde n'est pas à l'abri d'une gouvernance par le robot

Message codé:
Ld wpjgd j'due rnu à h'nbzs g'fjd ipftdzjnjxd rnz hd zpbpe

Message décodé:
Le monde n'est pas à l'abri d'une gouvernance par le robot

Est ce que le message décodé est identique à l'original? True


## Calculate multiplication

In [41]:
# Method 1
def indexed_product_1(n):
    """Naive version"""
    multiplication = 2
    for k in range(1,n+1) :
        multiplication *= (4*k**2) / (4*k**2 - 1)
    return multiplication

In [42]:
# Method 2
def indexed_product_2(n):
    """better version."""
    result = 2.
    for k in range(1, n + 1, 1):
        int = 4 * k ** 2
        result *= int / (int - 1.)
    return result

In [128]:
# Method 3 : recursive function 
def indexed_product_3(n):
    """lame version."""
    if n == 1 : 
        return 8. / 3.
    else :
        sqrpart = 4 * n ** 2
        return ((sqrpart / sqrpart - 1.) * indexed_product_3(n - 1))

In [129]:
# Method 4 : numpy
def indexed_product_4(n) : 
    sol = np.arange(1, n + 1)
    sol = sol ** 2
    sol = 4. * sol / (4. * sol - 1.)
    return 2 * np.prod(sol)

In [135]:
t = time.time()
indexed_product_1(2000)
print(time.time() - t)

t = time.time()
indexed_product_2(2000)
print(time.time() - t)

t = time.time()
indexed_product_3(2000)
print(time.time() - t)

t = time.time()
indexed_product_4(2000)
print(time.time() - t)

0.0018718242645263672
0.0
0.004486083984375
0.0009984970092773438


# Quicksort

In [163]:
def quicksort(l):
    """ a sorting algorithm with a pivot value"""
    if len(l) <= 1:
        return l
    else:
        pivot = l.pop()
        less = []
        greater = []
        for x in l:
            if x <= pivot:
                less.append(x) # append 'x' to 'less'
            else:
                greater.append(x) # append 'x' to 'greater'
        return less + [pivot] + greater  # concatenate quicksort(less), pivot and quicksort(greater)

In [164]:
l = [1,10,3,8,4,100,0,20]
quicksort(l)

[1, 10, 3, 8, 4, 0, 20, 100]

## Création d'une matrice et modification

In [171]:
a = [1,2]
b = [4,5]
np.matrix([a, b])

matrix([[1, 2],
        [4, 5]])

In [249]:
matrix = np.random.randint(low = -1 , high = 2, size = (5,6))
np.matrix(matrix)

matrix([[-1,  1,  1,  0,  0,  0],
        [-1,  0,  0, -1, -1,  0],
        [ 1,  0,  0, -1,  1,  0],
        [ 0, -1,  1,  1, -1,  1],
        [ 1,  1,  1,  0,  1, -1]], dtype=int32)

In [304]:
matrix = np.random.uniform(-1,1, size = (5,6))
print(matrix)

[[ 0.37640812  0.53811567  0.84157401 -0.9328296   0.29785719 -0.06243295]
 [-0.77360748  0.17807033  0.8247838  -0.1723428  -0.95072343 -0.66639047]
 [-0.3604202   0.77392715 -0.03936601 -0.33810993  0.66987243  0.20686263]
 [ 0.5353892  -0.96719959 -0.23299987 -0.60498484 -0.6548796   0.45351279]
 [ 0.29361271  0.24854989 -0.25264099 -0.15973085  0.4478263   0.13099978]]


In [253]:
matrix[:, 0] # All rows, 1 column

array([-1, -1,  1,  0,  1], dtype=int32)

In [306]:
m_sol1 = matrix.copy()
m_sol1[:, 0] = matrix[:, 0] - 2 * matrix[:, 1]
m_sol1[:, 2] = matrix[:, 2] - 2 * matrix[:, 3]
m_sol1[:, 4] = matrix[:, 4] - 2 * matrix[:, 5]

In [310]:
m_sol1[1,:]

array([-1.12974813,  0.17807033,  1.16946939, -0.1723428 ,  0.3820575 ,
       -0.66639047])

In [311]:
m_sol1[m_sol1 <= 0] = 0
print(m_sol1)
print(m_sol1)

[[0.         0.53811567 2.70723321 0.         0.42272309 0.        ]
 [0.         0.17807033 1.16946939 0.         0.3820575  0.        ]
 [0.         0.77392715 0.63685386 0.         0.25614717 0.20686263]
 [2.46978837 0.         0.97696981 0.         0.         0.45351279]
 [0.         0.24854989 0.06682071 0.         0.18582675 0.13099978]]
[[0.         0.53811567 2.70723321 0.         0.42272309 0.        ]
 [0.         0.17807033 1.16946939 0.         0.3820575  0.        ]
 [0.         0.77392715 0.63685386 0.         0.25614717 0.20686263]
 [2.46978837 0.         0.97696981 0.         0.         0.45351279]
 [0.         0.24854989 0.06682071 0.         0.18582675 0.13099978]]


## Création et modification d'une matrice complexe

In [314]:
matrix = np.random.uniform(-1,1, size =(5,20))
print(matrix)

[[-0.50490903  0.92409993 -0.22704755 -0.01242648  0.1958915   0.41900473
   0.7194341   0.48882917  0.47077874  0.77567093 -0.5695734   0.27211749
  -0.1773437  -0.54802933  0.1011566  -0.52146213 -0.72850983 -0.75231955
  -0.26243556 -0.31358489]
 [-0.35859762 -0.42306542  0.49727458  0.95375812 -0.50079302  0.45342251
  -0.83189148 -0.74444703 -0.26289613 -0.86888068 -0.88886781  0.1505676
  -0.8124238  -0.40502076  0.34406393  0.52245115  0.55832884 -0.09539826
   0.24186101 -0.16063405]
 [ 0.69851509  0.64622879  0.0811963   0.14532718 -0.69978327  0.57183052
   0.98614512 -0.94562255 -0.48323807  0.50770477  0.50967964 -0.32085812
   0.24060429 -0.90226424 -0.02668762  0.15769851  0.50737374 -0.05226608
   0.25472224  0.79223722]
 [-0.68160811 -0.87598408 -0.10651981 -0.78907444  0.36068828 -0.34961401
   0.14176676  0.66817273  0.03188713  0.92359027  0.42786602 -0.8721982
   0.48463683  0.63016401  0.80354569 -0.7373476  -0.02367899 -0.08603065
  -0.68340693 -0.2702857 ]
 [ 0.1